import * as vscode from 'vscode';
import { GoogleGenerativeAI } from '@google/generative-ai';
import * as fs from 'fs';
import * as path from 'path';

const translations: Record<string, any> = {
    'Français 🇫🇷': {
        noFolder: "Veuillez d'abord ouvrir un dossier !",
        apiKeyPrompt: "Entrez votre clé API Google Gemini",
        apiKeyWarning: "Clé API requise pour continuer.",
        progressTitle: "[README.IA] Analyse du code et génération...",
        progressRead: "Lecture du code source...",
        progressGenerate: "Génération du Markdown...",
        success: "✨ [README.IA] README généré avec succès !",
        error: "[README.IA] Erreur avec l'IA. Vérifiez votre clé API ou le modèle sélectionné.",
        resetKeyMsg: "🔑 [README.IA] Clé API supprimée de la mémoire locale.",
        footer: "\n\n---\n*🤖 README généré par l'extension [README.IA](https://github.com/lazlodev/README.IA) - Développé avec ❤️ par [@lazlodev](https://github.com/lazlodev)*"
    },
    'English 🇬🇧': {
        noFolder: "Please open a folder first!",
        apiKeyPrompt: "Enter your Google Gemini API key",
        apiKeyWarning: "API key is required to continue.",
        progressTitle: "[README.IA] Analyzing code and generating...",
        progressRead: "Reading source code...",
        progressGenerate: "Generating Markdown...",
        success: "✨ [README.IA] README generated successfully!",
        error: "[README.IA] AI Error. Check your API key or the selected model.",
        resetKeyMsg: "🔑 [README.IA] API key deleted from local storage.",
        footer: "\n\n---\n*🤖 README generated by the [README.IA](https://github.com/lazlodev/README.IA) extension - Developed with ❤️ by [@lazlodev](https://github.com/lazlodev)*"
    },
    'Español 🇪🇸': {
        noFolder: "¡Abra una carpeta primero!",
        apiKeyPrompt: "Introduzca su clave API de Google Gemini",
        apiKeyWarning: "Se requiere la clave API para continuar.",
        progressTitle: "[README.IA] Analizando código y generando...",
        progressRead: "Leyendo código fuente...",
        progressGenerate: "Generando Markdown...",
        success: "✨ [README.IA] ¡README generado con éxito!",
        error: "[README.IA] Error de IA. Verifique su clave API o el modelo seleccionado.",
        resetKeyMsg: "🔑 [README.IA] Clave API eliminada.",
        footer: "\n\n---\n*🤖 README generado por la extensión [README.IA](https://github.com/lazlodev/README.IA) - Desarrollado con ❤️ por [@lazlodev](https://github.com/lazlodev)*"
    },
    'Deutsch 🇩🇪': {
        noFolder: "Bitte öffnen Sie zuerst einen Ordner!",
        apiKeyPrompt: "Geben Sie Ihren Google Gemini API-Schlüssel ein",
        apiKeyWarning: "API-Schlüssel ist erforderlich, um fortzufahren.",
        progressTitle: "[README.IA] Code analysieren und generieren...",
        progressRead: "Quellcode lesen...",
        progressGenerate: "Markdown generieren...",
        success: "✨ [README.IA] README erfolgreich generiert!",
        error: "[README.IA] KI-Fehler. Überprüfen Sie Ihren API-Schlüssel oder das ausgewählte Modell.",
        resetKeyMsg: "🔑 [README.IA] API-Schlüssel gelöscht.",
        footer: "\n\n---\n*🤖 README generiert von der [README.IA](https://github.com/lazlodev/README.IA) Erweiterung - Entwickelt mit ❤️ von [@lazlodev](https://github.com/lazlodev)*"
    }
};

function getProjectContext(dirPath: string, basePath: string, depth = 0): string {
    if (depth > 3) return ''; 

    let content = '';
    const ignoredDirs = ['node_modules', '.git', 'dist', 'build', 'out', 'assets', 'images', '.vscode'];
    const allowedExtensions = [
        '.ts', '.tsx', '.js', '.jsx', '.html', '.css', '.scss', '.sass', '.vue', '.svelte',
        '.py', '.java', '.c', '.cpp', '.h', '.cs', '.go', '.rs', '.rb', '.php',
        '.swift', '.kt', '.dart', '.sh', '.bash', '.sql',
        '.json', '.yaml', '.yml', '.toml', '.xml', '.ini'
    ];

    try {
        const items = fs.readdirSync(dirPath);
        
        for (const item of items) {
            if (ignoredDirs.includes(item)) continue;

            const fullPath = path.join(dirPath, item);
            const stat = fs.statSync(fullPath);

            if (stat.isDirectory()) {
                content += getProjectContext(fullPath, basePath, depth + 1);
            } else if (stat.isFile()) {
                const ext = path.extname(item);
                const isAllowedFile = allowedExtensions.includes(ext) || item === 'package.json';
                
                if (isAllowedFile && stat.size < 30000) {
                    const fileContent = fs.readFileSync(fullPath, 'utf8');
                    const relativePath = fullPath.replace(basePath, '');
                    
                    content += `\n--- Fichier : ${relativePath} ---\n`;
                    content += fileContent.substring(0, 1500) + '\n';
                }
            }
        }
    } catch (error) {
        console.warn(`[README.IA] Impossible de lire le dossier : ${dirPath}`);
    }
    
    return content;
}

async function handleGenerateReadme(context: vscode.ExtensionContext) {
    const languages = Object.keys(translations);
    
    const selectedLang = await vscode.window.showQuickPick(languages, {
        placeHolder: '[README.IA] Choisissez la langue pour générer le README / Choose language',
        ignoreFocusOut: true
    });

    if (!selectedLang) return; 
    const t = translations[selectedLang];

    if (!vscode.workspace.workspaceFolders) {
        vscode.window.showErrorMessage(t.noFolder);
        return;
    }

    let apiKey = await context.secrets.get('geminiApiKey');

    if (!apiKey) {
        apiKey = await vscode.window.showInputBox({
            prompt: t.apiKeyPrompt,
            password: true,
            ignoreFocusOut: true
        });

        if (!apiKey) {
            vscode.window.showWarningMessage(t.apiKeyWarning);
            return;
        }
        await context.secrets.store('geminiApiKey', apiKey);
    }

    vscode.window.withProgress({
        location: vscode.ProgressLocation.Notification,
        title: t.progressTitle,
        cancellable: false
    }, async (progress) => {
        try {
            const folderPath = vscode.workspace.workspaceFolders![0].uri.fsPath;
            
            progress.report({ message: t.progressRead });
            const projectData = getProjectContext(folderPath, folderPath);

            const genAI = new GoogleGenerativeAI(apiKey!);
            const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" }); 

            const prompt = `Tu es un Lead Dev spécialisé en documentation technique. Ton objectif est de générer un README.md parfait et visuel pour le projet suivant.

Code source du projet :
${projectData}

Consignes :
- Rédige UNIQUEMENT en ${selectedLang.toUpperCase()}.
- Ajoute un titre stylé (avec badges si pertinent).
- Explique le but du projet.
- Fais une liste des technos utilisées (avec emojis).
- Liste les features principales déduites du code.
- Ajoute une section Installation/Usage.
- Ne mets AUCUNE intro ou conclusion du style "Voici le markdown". Retourne juste le code brut.`;

            progress.report({ message: t.progressGenerate });
            const result = await model.generateContent(prompt);
            
            let readmeContent = result.response.text();
            
            readmeContent = readmeContent.replace(/^```markdown\n/, '').replace(/```$/, '');
            readmeContent += t.footer;

            const fileUri = vscode.Uri.file(path.join(folderPath, 'README.md'));
            await vscode.workspace.fs.writeFile(fileUri, Buffer.from(readmeContent, 'utf8'));
            
            const doc = await vscode.workspace.openTextDocument(fileUri);
            await vscode.window.showTextDocument(doc);
            
            vscode.window.showInformationMessage(t.success);

        } catch (error) {
            console.error("[README.IA] Erreur Gemini API:", error);
            vscode.window.showErrorMessage(t.error);
            await context.secrets.delete('geminiApiKey');
        }
    });
}

async function handleResetKey(context: vscode.ExtensionContext) {
    await context.secrets.delete('geminiApiKey');
    vscode.window.showInformationMessage(translations['Français 🇫🇷'].resetKeyMsg);
}

export function activate(context: vscode.ExtensionContext) {
    const generateCmd = vscode.commands.registerCommand('readme-gen.create', () => handleGenerateReadme(context));
    const resetKeyCmd = vscode.commands.registerCommand('readme-gen.resetKey', () => handleResetKey(context));

    const generateBtn = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Right, 100);
    generateBtn.command = 'readme-gen.create';
    generateBtn.text = '$(sparkle) IA Readme';
    generateBtn.tooltip = '[README.IA] Générer un README avec l\'IA';
    generateBtn.show();

    const keyBtn = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Right, 99); 
    keyBtn.command = 'readme-gen.resetKey';
    keyBtn.text = '$(key)'; 
    keyBtn.tooltip = '[README.IA] Supprimer la clé API Gemini';
    keyBtn.show();

    context.subscriptions.push(generateCmd, resetKeyCmd, generateBtn, keyBtn);
}

export function deactivate() {
}